---
- name: 'make sure pg_user and pg_password are defined'
  fail: msg='variables undefined'
  when:
    - pg_user is undefined
    - pg_password is undefined

- name: 'install the postgres yum repo'
  become: yes
  yum: name={{postgres_repo}} state=present
  when: ansible_os_family == "RedHat"
  tags:
    - install
    - postgres

- name: 'install postgres packages'
  become: yes
  yum: name={{ item }} state=present
  with_items: '{{ postgres_packages }}'
  when: ansible_os_family == "RedHat"
  tags:
    - install
    - postgres

- name: 'install required libraries'
  become: yes
  pip: name={{ item }} state=present
  tags:
    - install
    - postgres
    - startslave
  with_items:
    - pexpect
